import {
  StyleSheet,
  TouchableOpacity,
  View,
  Dimensions,
  Text,
} from "react-native";

export const bigIdeaStyles = StyleSheet.create({
  textBox: {
    position: "absolute",
    left: 16,
    right: 16,
    top: "10%",
    bottom: 16,
    padding: 16,
    backgroundColor: "white",
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#B5B5B5",
    flex: 1,
    flexDirection: "column",
    justifyContent: "flex-start",
    alignContent: "flex-start",
  },
  upVote: {
    backgroundColor: "#F6F6F6",
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-start",
    paddingBottom: 2,
    marginRight: 5,
    flexShrink: 1,
    flexBasis: 10,
  },
  mainIdeaInfo: {
    backgroundColor: "white",
    height: 1000,
    flex: 1,
    flexDirection: "column",
    alignItems: "flex-start",
    flexBasis: 100,
  },
  username: {
    color: "grey",
  },
  ideaName: {
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 5,
  },
  buttons: {
    width: "20%",
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 16,
  },
  Buttons1: {
    backgroundColor: "white",
    flex: 1,
    flexDirection: "column",
    alignItems: "flex-end",
    justifyContent: "flex-end",
  },
  followButton: {
    flexDirection: "row",
    backgroundColor: "#1C883C",
    height: 30,
    borderRadius: 8,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 5,
  },
  button: {
    padding: 8,
    borderRadius: 8,
  },
  followText: {
    color: "white",
    fontSize: 11,
    paddingLeft: 5,
  },
  closeButton: {
    width: "50%",
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0E5E33",
    borderRadius: 15,
    marginTop: 5,
  },
  //comments stuff
  commentInputContainer: {
    position: "relative",
    left: 10,
    right: 16,
    top: "0%",
    bottom: "0%",
    padding: 0,
    backgroundColor: "white",
    flexDirection: "row",
    alignItems: "center",
    zIndex: 3,
  },

  commentInput: {
    flex: 2,
    height: 30,
    borderColor: "gray",
    borderWidth: 1,
    borderRadius: 8,
    marginRight: 10,
    paddingLeft: 10,
    width: 390,
  },

  sendCommentButton: {
    backgroundColor: "#128B4A",
    padding: 6,
    borderRadius: 8,
    margin: 8,
    height: 30,
    marginRight: 0,
    marginLeft: 10,
    justifyContent: "center",
  },

  sendCommentButtonText: {
    color: "white",
  },
  scrollContainer: {
    position: "relative",
    left: "0%",
    right: "0%",
    top: "0%",
    bottom: "12%",
    maxHeight: 220,
    height: 220,
    backgroundColor: "white",
  },
  ideaContent: {},
  commentContainer: {
    borderColor: "#F6F6F6",
    backgroundColor: "#F6F6F6",
    borderWidth: 1,
    borderRadius: 5,
    paddingVertical: 5,
    paddingLeft: 10,
    marginBottom: 10,
  },
  keyText: {
    marginLeft: 50,
    paddingBottom: 15,
  },
  valText: {},
  deleteComment: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
  },
  commButtons: {
    flex: 1,
    flexDirection: "row",
  },
  deleteButton: {
    height: 30,
    width: "50%",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    marginTop: 5,
    backgroundColor: "#C3C3C3",
  },
  closeText: {
    color: "blue",
    fontSize: 13,
  },
  description: {
    borderWidth: 1,
    borderColor: "#E2E2E2",
    borderRadius: 5,
    width: "100%",
    height: "30%",
    padding: 10,
    marginTop: 10,
  },
  voteIconContainer: {
    width: 22,
    height: 22,
    backgroundColor: "#CEFFDD",
    color: "#1C883C",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 4,
    marginLeft: 5,
    marginTop: 0,
    paddingTop: 3,
  },
  ideaAvatar: {
    width: 50,
    height: 50,
    borderRadius: 160,
    resizeMode: "cover",
    marginRight: 5,
  },
  avatar: {
    width: 30,
    height: 30,
    borderRadius: 160,
    resizeMode: "cover",
    marginRight: 5,
  },
  user: {
    flexDirection: "row",
    alignItems: "center",
  },
});
