import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  textBox: {
    position: "absolute",
    width: "100%",
    height: 180,
    bottom: 50,
    backgroundColor: "white",
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#B5B5B5",
    flex: 1,
    flexDirection: "column",
    paddingVertical: 15,
    paddingHorizontal: 15,
  },
  searchBox: {
    position: "absolute",
    flexDirection: "row",
    backgroundColor: "#EEEEEE",
    width: "100%",
    top: "20%",
    height: 55,
    paddingLeft: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#C0C0C0",
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  searchBar: {
    width: "90%",
    color: "gray",
    fontWeight: "bold",
  },
  icon: {
    width: "10%",
  },
  voteContainer: {
    width: "25%",
    alignItems: "center",
    justifyContent: "center",
  },
  voteNum: {
    fontSize: 13,
    color: "#128B4A",
    fontWeight: "bold",
    paddingBottom: 10,
  },
  voteIconContainer: {
    width: 60,
    height: 60,
    backgroundColor: "#CEFFDD",
    color: "#128B4A",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
  },
  thumbUp: {
    flex: 1,
    backgroundColor: "light green",
    alignSelf: "center",
  },
  mainIdeaBox: {
    width: "75%",
    flexDirection: "row",
  },
  mainIdeaInfo: {
    alignContent: "center",
    justifyContent: "center",
    flexDirection: "column",
    paddingHorizontal: 10,
  },
  username: {
    fontSize: 13,
    height: 20,
    color: "grey",
  },
  ideaName: {
    fontSize: 20,
    fontWeight: "bold",
  },
  ideaDescription: {
    fontSize: 13,
    paddingTop: 5,
    height: 40,
  },
  buttons: {
    width: "20%",
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
  followButton: {
    flexDirection: "row",
    height: 30,
    borderRadius: 8,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 5,
  },
  deleteButton: {
    height: 30,
    width: "50%",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    marginTop: 5,
    backgroundColor: "#C3C3C3",
  },
  followNcommentContainer: {
    justifyContent: "space-evenly",
    alignItems: "center",
    padding: 5,
  },
  followText: {
    color: "white",
    fontSize: 11,
    paddingLeft: 5,
  },
  commentButton: {
    width: "100%",
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#128B4A",
    borderRadius: 8,
    marginTop: 5,
  },
  commentText: {
    color: "white",
    fontSize: 11,
    padding: 5,
  },
  closeButton: {
    width: "50%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0E5E33",
    borderRadius: 15,
    marginTop: 5,
  },
  closeText: {
    color: "blue",
    fontSize: 13,
  },
  refreshButton: {
    position: "absolute",
    top: "0%",
    left: "80%",
    right: "5%",
    padding: 3,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#128B4A",
    borderRadius: 8,
    marginTop: 5,
  },
  editBtn: {
    backgroundColor: "#C3C3C3",
    height: 30,
    width: "20%",
    borderRadius: 8,
    justifyContent: "center",
  },
  editText: {
    color: "white",
    fontSize: 12,
    textAlign: "center",
  },
  bellButton: {
    position: "absolute",
    top: "0%",
    left: "5%",
    right: "80%",
    padding: 3,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#128B4A",
    borderRadius: 8,
    marginTop: 5,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 160,
    resizeMode: "cover",
    marginRight: 5,
  },
  user: {
    flexDirection: "row",
    alignItems: "center",
  },
});
